### ISSUE TITLE
can I control my car with this tool?

### ISSUE THREAD

**Issue by cyberhck** [linklayer/cantact-hw#1]
Is this tool only for monitoring or can it also control a car, say steer programmatically, brake and throttle?

**Comment by crossband** [comment]
You can not only receive CAN messages, but also send them. This means you could possibly control your vehicle. But it depends on your car.

Have you ever tried using "can-utils" package?

**Comment by cyberhck** [comment]
Hi, thanks for the response. And thanks a lot for the awesome opensource tool (love opensource can't live without them), I'm not yet there (didn't pay attention in my maths class in university), once I go through a little statics, probability and linear algebra, I'll do computer vision and I'll buy this hardware to see if I can hack my car to make a simple lane keeping level 1 vehicle :) thanks. BTW, does this ship worldwide?

**Comment by crossband** [comment]
Regarding WW shipment you can ask to Eric. Here is the link to his webspage: http://linklayer.github.io/cantact/

Good luck!

**Comment by cyberhck** [comment]
closing this as I did get the info, and there's really no need for this issue to stay open :slightly_smiling_face:
